# Generated by Django 5.2.8 on 2025-11-26 16:08

import django.core.validators
import reporter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('brand', models.CharField(max_length=125)),
                ('product_name', models.CharField(max_length=125)),
                ('product_type', models.CharField(choices=[('', 'Beverage Type'), ('General', 'General'), ('Beer', 'Beer'), ('Wine', 'Wine'), ('Liquor', 'Liquor'), ('Liqueur', 'Liqueur'), ('Cider', 'Cider'), ('Mead', 'Mead'), ('Sake', 'Sake'), ('Hard Seltzer', 'Hard Seltzer'), ('Kombucha', 'Kombucha'), ('Beer - Amber Ale', 'Beer - Amber Ale'), ('Beer - Barleywine', 'Beer - Barleywine'), ('Beer - Belgian Ale', 'Beer - Belgian Ale'), ('Beer - Belgian Witbier', 'Beer - Belgian Witbier'), ('Beer - Berliner Weisse', 'Beer - Berliner Weisse'), ('Beer - Bock', 'Beer - Bock'), ('Beer - Brown Ale', 'Beer - Brown Ale'), ('Beer - Doppelbock', 'Beer - Doppelbock'), ('Beer - Dunkel', 'Beer - Dunkel'), ('Beer - Farmhouse Ale', 'Beer - Farmhouse Ale'), ('Beer - Gose', 'Beer - Gose'), ('Beer - Hazy / New England IPA', 'Beer - Hazy / New England IPA'), ('Beer - Hefeweizen', 'Beer - Hefeweizen'), ('Beer - Helles', 'Beer - Helles'), ('Beer - Imperial Stout', 'Beer - Imperial Stout'), ('Beer - India Pale Ale (IPA)', 'Beer - India Pale Ale (IPA)'), ('Beer - Lager', 'Beer - Lager'), ('Beer - Lambic', 'Beer - Lambic'), ('Beer - Märzen / Oktoberfest', 'Beer - Märzen / Oktoberfest'), ('Beer - Milk Stout', 'Beer - Milk Stout'), ('Beer - Pale Ale', 'Beer - Pale Ale'), ('Beer - Pilsner', 'Beer - Pilsner'), ('Beer - Porter', 'Beer - Porter'), ('Beer - Saison', 'Beer - Saison'), ('Beer - Scotch Ale', 'Beer - Scotch Ale'), ('Beer - Sour Beer', 'Beer - Sour Beer'), ('Beer - Stout', 'Beer - Stout'), ('Beer - Triple IPA', 'Beer - Triple IPA'), ('Beer - Vienna Lager', 'Beer - Vienna Lager'), ('Beer - West Coast IPA', 'Beer - West Coast IPA'), ('Beer - Wheat Beer', 'Beer - Wheat Beer'), ('Wine - Albariño', 'Wine - Albariño'), ('Wine - Barbera', 'Wine - Barbera'), ('Wine - Cabernet Sauvignon', 'Wine - Cabernet Sauvignon'), ('Wine - Carménère', 'Wine - Carménère'), ('Wine - Cava', 'Wine - Cava'), ('Wine - Champagne', 'Wine - Champagne'), ('Wine - Chardonnay', 'Wine - Chardonnay'), ('Wine - Chenin Blanc', 'Wine - Chenin Blanc'), ('Wine - Dessert Wine', 'Wine - Dessert Wine'), ('Wine - Fortified Wine', 'Wine - Fortified Wine'), ('Wine - Grenache', 'Wine - Grenache'), ('Wine - Grüner Veltliner', 'Wine - Grüner Veltliner'), ('Wine - Ice Wine', 'Wine - Ice Wine'), ('Wine - Madeira', 'Wine - Madeira'), ('Wine - Malbec', 'Wine - Malbec'), ('Wine - Marsala', 'Wine - Marsala'), ('Wine - Merlot', 'Wine - Merlot'), ('Wine - Mourvèdre', 'Wine - Mourvèdre'), ('Wine - Moscato', 'Wine - Moscato'), ('Wine - Nebbiolo', 'Wine - Nebbiolo'), ('Wine - Petit Verdot', 'Wine - Petit Verdot'), ('Wine - Pinot Grigio / Pinot Gris', 'Wine - Pinot Grigio / Pinot Gris'), ('Wine - Pinot Noir', 'Wine - Pinot Noir'), ('Wine - Port', 'Wine - Port'), ('Wine - Prosecco', 'Wine - Prosecco'), ('Wine - Red Wine', 'Wine - Red Wine'), ('Wine - Riesling', 'Wine - Riesling'), ('Wine - Rosé', 'Wine - Rosé'), ('Wine - Sangiovese', 'Wine - Sangiovese'), ('Wine - Sauvignon Blanc', 'Wine - Sauvignon Blanc'), ('Wine - Sherry', 'Wine - Sherry'), ('Wine - Sparkling Wine', 'Wine - Sparkling Wine'), ('Wine - Sémillon', 'Wine - Sémillon'), ('Wine - Syrah / Shiraz', 'Wine - Syrah / Shiraz'), ('Wine - Tempranillo', 'Wine - Tempranillo'), ('Wine - Viognier', 'Wine - Viognier'), ('Wine - White Wine', 'Wine - White Wine'), ('Wine - Zinfandel', 'Wine - Zinfandel'), ('Liquor - Absinthe', 'Liquor - Absinthe'), ('Liquor - Aquavit', 'Liquor - Aquavit'), ('Liquor - Armagnac', 'Liquor - Armagnac'), ('Liquor - Blanco Tequila', 'Liquor - Blanco Tequila'), ('Liquor - Brandy', 'Liquor - Brandy'), ('Liquor - Bourbon', 'Liquor - Bourbon'), ('Liquor - Calvados', 'Liquor - Calvados'), ('Liquor - Canadian Whisky', 'Liquor - Canadian Whisky'), ('Liquor - Cognac', 'Liquor - Cognac'), ('Liquor - Dark Rum', 'Liquor - Dark Rum'), ('Liquor - Gin', 'Liquor - Gin'), ('Liquor - Grappa', 'Liquor - Grappa'), ('Liquor - Irish Whiskey', 'Liquor - Irish Whiskey'), ('Liquor - Japanese Whisky', 'Liquor - Japanese Whisky'), ('Liquor - London Dry Gin', 'Liquor - London Dry Gin'), ('Liquor - Mezcal', 'Liquor - Mezcal'), ('Liquor - Reposado Tequila', 'Liquor - Reposado Tequila'), ('Liquor - Rum', 'Liquor - Rum'), ('Liquor - Rye Whiskey', 'Liquor - Rye Whiskey'), ('Liquor - Scotch', 'Liquor - Scotch'), ('Liquor - Spiced Rum', 'Liquor - Spiced Rum'), ('Liquor - Tequila', 'Liquor - Tequila'), ('Liquor - Vodka', 'Liquor - Vodka'), ('Liquor - White Rum', 'Liquor - White Rum'), ('Liquor - Whiskey', 'Liquor - Whiskey'), ('Liqueur - Amaro', 'Liqueur - Amaro'), ('Liqueur - Anise Liqueur', 'Liqueur - Anise Liqueur'), ('Liqueur - Coffee Liqueur', 'Liqueur - Coffee Liqueur'), ('Liqueur - Cream Liqueur', 'Liqueur - Cream Liqueur'), ('Liqueur - Fruit Liqueur', 'Liqueur - Fruit Liqueur'), ('Liqueur - Herbal Liqueur', 'Liqueur - Herbal Liqueur'), ('Liqueur - Orange Liqueur', 'Liqueur - Orange Liqueur')], default='General', max_length=125)),
                ('abv', models.FloatField(blank=True, null=True)),
                ('milliliters', models.FloatField(blank=True, null=True)),
                ('fl_oz', models.FloatField(blank=True, null=True)),
                ('warning_label', models.BooleanField(default=True)),
                ('warning_text', models.CharField(blank=True, max_length=512, null=True)),
                ('ai_payload', models.TextField(blank=True)),
                ('ai_brand', models.CharField(blank=True, max_length=125)),
                ('ai_product_name', models.CharField(blank=True, max_length=125)),
                ('ai_product_type', models.CharField(blank=True, max_length=125)),
                ('ai_abv', models.FloatField(blank=True, null=True)),
                ('ai_milliliters', models.FloatField(blank=True, null=True)),
                ('ai_fl_oz', models.FloatField(blank=True, null=True)),
                ('ai_warning_label', models.BooleanField(default=True)),
                ('ai_warning_text', models.CharField(blank=True, max_length=512)),
                ('ai_error', models.CharField(blank=True, max_length=255, null=True)),
                ('match_brand', models.FloatField(blank=True, null=True)),
                ('note_brand', models.CharField(blank=True, max_length=300)),
                ('match_product_name', models.FloatField(blank=True, null=True)),
                ('note_product_name', models.CharField(blank=True, max_length=300)),
                ('match_product_type', models.FloatField(blank=True, null=True)),
                ('note_product_type', models.CharField(blank=True, max_length=300)),
                ('match_abv', models.FloatField(blank=True, null=True)),
                ('note_abv', models.CharField(blank=True, max_length=300)),
                ('match_milliliters', models.FloatField(blank=True, null=True)),
                ('note_milliliters', models.CharField(blank=True, max_length=300)),
                ('match_fl_oz', models.FloatField(blank=True, null=True)),
                ('note_fl_oz', models.CharField(blank=True, max_length=300)),
                ('match_warning_label', models.FloatField(blank=True, null=True)),
                ('note_warning_label', models.CharField(blank=True, max_length=300)),
                ('match_warning_text', models.FloatField(blank=True, null=True)),
                ('note_warning_text', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True)),
                ('front_image', models.ImageField(blank=True, upload_to=reporter.models.img_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), reporter.models.check_image_size])),
                ('back_image', models.ImageField(blank=True, upload_to=reporter.models.img_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), reporter.models.check_image_size])),
            ],
        ),
    ]
